export const API_BASE_URL = 'http://192.168.0.131:1337';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_GROUP_INDEX = 'UPDATE_GROUP_INDEX';

export const ADD_SCHOOL = 'ADD_SCHOOL';
export const DELETE_SCHOOL = 'DELETE_SCHOOL';
export const UPDATE_SCHOOL = 'UPDATE_SCHOOL';
export const UPDATE_SCHOOL_INDEX = 'UPDATE_SCHOOL_INDEX';

export const ADD_SCHOOL_SESSION = 'ADD_SCHOOL_SESSION';
export const DELETE_SCHOOL_SESSION = 'DELETE_SCHOOL_SESSION';
export const UPDATE_SCHOOL_SESSION = 'UPDATE_SCHOOL_SESSION';
export const UPDATE_SCHOOL_SESSION_INDEX = 'UPDATE_SCHOOL_SESSION_INDEX';

export const ADD_EDUCATION_BOARD = 'ADD_EDUCATION_BOARD';
export const DELETE_EDUCATION_BOARD = 'DELETE_EDUCATION_BOARD';
export const UPDATE_EDUCATION_BOARD = 'UPDATE_EDUCATION_BOARD';
export const UPDATE_EDUCATION_BOARD_INDEX = 'UPDATE_EDUCATION_BOARD_INDEX';
